# Generated by Django 6.0.6 on 2026-08-16 16:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('barcode', models.CharField(db_index=True, max_length=200)),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('current_stage', models.CharField(choices=[('manufactured', 'Manufactured'), ('quality_checked', 'Quality checked'), ('packaged', 'Packaged'), ('shipped', 'Shipped'), ('distributor_received', 'Distributor received'), ('wholesaler_received', 'Wholesaler received'), ('retailer_received', 'Retailer received'), ('sold', 'Sold to customer'), ('returned', 'Returned'), ('flagged', 'Flagged')], default='manufactured', max_length=30)),
                ('current_owner', models.CharField(blank=True, max_length=200)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('authenticity_status', models.CharField(choices=[('pending', 'Pending'), ('authentic', 'Authentic'), ('suspicious', 'Suspicious'), ('fake', 'Fake'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_chain_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyChainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('manufactured', 'Manufactured'), ('quality_checked', 'Quality checked'), ('packaged', 'Packaged'), ('shipped', 'Shipped'), ('distributor_received', 'Distributor received'), ('wholesaler_received', 'Wholesaler received'), ('retailer_received', 'Retailer received'), ('sold', 'Sold to customer'), ('returned', 'Returned'), ('flagged', 'Flagged')], max_length=30)),
                ('actor_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('customer', 'Customer'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('actor_name', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('geo_accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('event_time', models.DateTimeField()),
                ('document_ref', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspicious', 'Suspicious')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_supply_events', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='supply_chain.supplychainrecord')),
            ],
            options={
                'ordering': ['event_time', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='supplychainrecord',
            index=models.Index(fields=['barcode', 'batch_number'], name='supply_chai_barcode_14aa92_idx'),
        ),
    ]
