import os
from datetime import datetime

from django.conf import settings
from django.http import HttpResponse

from reportlab.pdfgen import canvas


def generate_pdf(product_id, report):

    response = HttpResponse(content_type="application/pdf")

    response["Content-Disposition"] = (
        f'attachment; filename="Product_Report_{product_id}.pdf"'
    )

    pdf = canvas.Canvas(response)

    pdf.setTitle("Counterfeit Product Verification Report")

    y = 800

    # =====================================================
    # Title
    # =====================================================

    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawCentredString(300, y, "COUNTERFEIT PRODUCT DETECTOR")

    y -= 28

    pdf.setFont("Helvetica-Bold", 15)
    pdf.drawCentredString(300, y, "PRODUCT VERIFICATION REPORT")

    y -= 18

    pdf.line(50, y, 550, y)

    y -= 35

    # =====================================================
    # Report Information
    # =====================================================

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Report Information")

    y -= 25

    pdf.setFont("Helvetica", 12)

    pdf.drawString(70, y, "Report ID")
    pdf.drawString(180, y, f": {product_id}")

    y -= 20

    pdf.drawString(70, y, "Generated On")
    pdf.drawString(
        180,
        y,
        ": " + datetime.now().strftime("%d %b %Y, %I:%M %p")
    )

    y -= 35

    # =====================================================
    # Product Information
    # =====================================================

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Product Information")

    y -= 25

    pdf.setFont("Helvetica", 12)

    pdf.drawString(70, y, "Product Name")
    pdf.drawString(180, y, f": {report['product_name']}")

    y -= 20

    pdf.drawString(70, y, "Brand")
    pdf.drawString(180, y, f": {report['brand']}")

    y -= 40

    # =====================================================
    # Product Images
    # =====================================================

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Product Images")

    y -= 25

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(70, y, "User Product")

    if report["user_image"]:

        user_image_path = os.path.join(
            settings.BASE_DIR,
            "product_comparison",
            "static",
            report["user_image"]
        )

        if os.path.exists(user_image_path):

            pdf.drawImage(
                user_image_path,
                70,
                y - 120,
                width=120,
                height=120,
                preserveAspectRatio=True
            )

        else:

            pdf.drawString(70, y - 20, "Image Not Available")

    else:

        pdf.drawString(70, y - 20, "Image Not Available")

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(320, y, "Original Product")

    if report["original_image"]:

        original_image_path = os.path.join(
            settings.BASE_DIR,
            "product_comparison",
            "static",
            report["original_image"]
        )

        if os.path.exists(original_image_path):

            pdf.drawImage(
                original_image_path,
                320,
                y - 120,
                width=120,
                height=120,
                preserveAspectRatio=True
            )

        else:

            pdf.drawString(320, y - 20, "Image Not Available")

    else:

        pdf.drawString(320, y - 20, "Image Not Available")

    y -= 170

    # =====================================================
    # Verification Result
    # =====================================================

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Verification Result")

    y -= 25

    pdf.setFont("Helvetica", 12)

    pdf.drawString(70, y, "Verdict")
    pdf.drawString(180, y, f": {report['verdict']}")

    y -= 20

    pdf.drawString(70, y, "Confidence Score")
    pdf.drawString(180, y, f": {report['score']}%")

    y -= 35

    # =====================================================
    # AI Analysis
    # =====================================================

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "AI Analysis")

    y -= 25

    pdf.setFont("Helvetica", 12)

    text = pdf.beginText(70, y)
    text.setLeading(18)
    text.textLines(report["reason"])
    pdf.drawText(text)

    pdf.line(50, 80, 550, 80)

    pdf.setFont("Helvetica-Oblique", 10)

    pdf.drawCentredString(
        300,
        60,
        "Generated by Counterfeit Product Detector"
    )

    pdf.drawCentredString(
        300,
        45,
        "North South University"
    )

    pdf.showPage()
    pdf.save()

    return response