# Generated by Django 6.0.7 on 2026-07-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('verdict', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
