# Generated by Django 6.0.6 on 2026-08-16 16:38

import community_alerts.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('shop_name', models.CharField(blank=True, max_length=200)),
                ('purchase_location', models.CharField(max_length=255)),
                ('suspicious_reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('geo_accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('geo_source', models.CharField(choices=[('gps', 'GPS'), ('manual', 'Manual'), ('network', 'Network'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('geo_address', models.CharField(blank=True, max_length=255)),
                ('geo_captured_at', models.DateTimeField(blank=True, null=True)),
                ('geo_verification_status', models.CharField(choices=[('not_provided', 'Not provided'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_provided', max_length=15)),
                ('geo_verification_note', models.CharField(blank=True, max_length=255)),
                ('is_within_claimed_area', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_alerts', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_community_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community_alerts/%Y/%m/', validators=[community_alerts.validators.validate_evidence_image])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='community_alerts.communityalert')),
            ],
        ),
        migrations.CreateModel(
            name='AlertConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='community_alerts.communityalert')),
            ],
        ),
        migrations.CreateModel(
            name='AlertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community_alerts.communityalert')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communityalert',
            index=models.Index(fields=['status', '-created_at'], name='community_a_status_2f2920_idx'),
        ),
        migrations.AddIndex(
            model_name='communityalert',
            index=models.Index(fields=['barcode'], name='community_a_barcode_d40add_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityalert',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='alert_coordinates_both_or_neither'),
        ),
        migrations.AddConstraint(
            model_name='alertconfirmation',
            constraint=models.UniqueConstraint(fields=('alert', 'user'), name='one_confirmation_per_user'),
        ),
    ]
